function import_aliases_git
    alias st 'git status'
    alias log 'git log'
    alias co 'git checkout'
    alias cob 'git checkout -b'
    alias br 'git branch'
    alias aa 'git add -A .'
    alias cm 'git commit -m'
    alias aacm 'git add -A .; git commit -m'
    alias po 'git push origin'
    alias plo 'git pull origin'
    alias coo 'git fetch; git checkout'
    alias pu 'git push origin (git branch --show-current)'
    alias amend 'git commit --amend -m'
    alias cp 'git cherry-pick'
    alias unstage 'git reset --soft HEAD^'
    alias brd 'git branch -d'
    alias brD 'git branch -D'
    alias merged 'git branch --merged'
    alias dev 'git checkout dev; git pull origin dev'
    alias staging 'git checkout staging; git pull origin staging'
    alias main 'git checkout main; git pull origin'
    alias master 'git checkout master; git pull origin'
    alias pod 'git push origin dev'
    alias pos 'git push origin staging'
    alias pom 'git push origin main'
    alias poh 'git push origin HEAD'
    alias plod 'git pull origin dev'
    alias plos 'git pull origin staging'
    alias plom 'git pull origin main'
    alias ploh 'git pull origin HEAD'
    alias pogm 'git push origin gh-pages; git checkout master; git pull origin master; git rebase gh-pages; git push origin master; git checkout gh-pages'
    alias pomg 'git push origin master; git checkout gh-pages; git pull origin gh-pages; git rebase master; git push origin gh-pages; git checkout master'
    alias lsd 'git log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate'
    alias lln 'git log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --numstat'
    alias f 'git ls-files | grep -i'
    alias gr 'git grep -Ii'
    alias gla 'git config -l | grep alias | cut -c 7-'
end
